// Transparent Decal Shader - generated by Decal Tool
//  - Transparent blend, ZWrite Off, double sided
//  - _Alpha controls overall opacity (runtime editable via MaterialPropertyBlock)
//  - Two alpha sources: texture A channel by default, or luminance (with optional invert)
Shader "Dexiang/Decal/Transparent"
{
    Properties
    {
        [NoScaleOffset] _BaseMap("Base Map", 2D) = "white" {}
        [HDR] _BaseColor("Tint Color", Color) = (1,1,1,1)
        _Alpha("Alpha", Range(0,1)) = 1

        [Toggle(_USE_LUMINANCE)] _UseLuminance("Use Luminance As Alpha", Float) = 0
        [Toggle(_INVERT_ALPHA)] _InvertAlpha("Invert Luminance", Float) = 0
    }

    SubShader
    {
        Tags
        {
            "RenderType" = "Transparent"
            "Queue" = "Transparent+100"
            "RenderPipeline" = "UniversalPipeline"
        }

        Blend SrcAlpha OneMinusSrcAlpha
        ZWrite Off
        ZTest LEqual
        Cull Off

        Pass
        {
            Name "ForwardDecal"
            Tags { "LightMode" = "UniversalForward" }

            HLSLPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #pragma shader_feature_local _USE_LUMINANCE
            #pragma shader_feature_local _INVERT_ALPHA
            #pragma target 2.0

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"

            struct appdata
            {
                float4 positionOS : POSITION;
                float2 uv         : TEXCOORD0;
            };

            struct v2f
            {
                float4 positionCS : SV_POSITION;
                float2 uv         : TEXCOORD0;
            };

            TEXTURE2D(_BaseMap);
            SAMPLER(sampler_BaseMap);

            CBUFFER_START(UnityPerMaterial)
                float4 _BaseColor;
                float  _Alpha;
            CBUFFER_END

            v2f vert(appdata v)
            {
                v2f o;
                o.positionCS = TransformObjectToHClip(v.positionOS.xyz);
                o.uv = v.uv;
                return o;
            }

            half4 frag(v2f i) : SV_Target
            {
                float4 tex = SAMPLE_TEXTURE2D(_BaseMap, sampler_BaseMap, i.uv);

                float a;
                #if defined(_USE_LUMINANCE)
                    a = Luminance(tex.rgb);
                    #if defined(_INVERT_ALPHA)
                        a = 1.0 - a;
                    #endif
                #else
                    a = tex.a;
                #endif

                float finalAlpha = a * _Alpha;
                half3  col = tex.rgb * _BaseColor.rgb;
                return half4(col, finalAlpha);
            }
            ENDHLSL
        }
    }

    Fallback Off
}
